module.exports = [
  {
    sampleid: 1005412,
    numero_contribuinte: '0471940203-8',
    nome_contribuinte: 'ITAU UNIBANCO SA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 142',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005413,
    numero_contribuinte: '0471940204-6',
    nome_contribuinte: 'EUCLIDES CARDILLI JUNIOR',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 13',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005414,
    numero_contribuinte: '0471940205-4',
    nome_contribuinte: 'CLAUDIO ALVES SIMOES',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 23',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005415,
    numero_contribuinte: '0471940206-2',
    nome_contribuinte: 'GIANE CALONEGO',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 33',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005416,
    numero_contribuinte: '0471940207-0',
    nome_contribuinte: 'CAIXA ECONOMICA FEDERAL',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 43',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005417,
    numero_contribuinte: '0471940208-9',
    nome_contribuinte: 'ALEXANDRE GOMES DE MELO',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 53',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005418,
    numero_contribuinte: '0471940209-7',
    nome_contribuinte: 'APARECIDA DE FATIMA CONTI RODRIGUES',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 63',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005419,
    numero_contribuinte: '0471940210-0',
    nome_contribuinte: 'EDERLY KFOURI HADDAD',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 73',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005420,
    numero_contribuinte: '0471940211-9',
    nome_contribuinte: 'ESTELA EMI TAKASE',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 83',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005421,
    numero_contribuinte: '0471940212-7',
    nome_contribuinte: 'NESTOR FURUYAMA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 93',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005422,
    numero_contribuinte: '0471940213-5',
    nome_contribuinte: 'FRANCISCO DE ASSIS SILVA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 103',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005423,
    numero_contribuinte: '0471940214-3',
    nome_contribuinte: 'ALICE KATUE KINOSHITA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 113',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005424,
    numero_contribuinte: '0471940215-1',
    nome_contribuinte: 'LETICIA AKEMI OSHIMA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 123',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005425,
    numero_contribuinte: '0471940216-1',
    nome_contribuinte: 'LUIZ MARTINS GARCIA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP 133',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005426,
    numero_contribuinte: '0471940217-8',
    nome_contribuinte: 'JUMARA DOTTI',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 143',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005427,
    numero_contribuinte: '0471940218-6',
    nome_contribuinte: 'FRANCISCO JULIO BARBUGIANI',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 14',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005428,
    numero_contribuinte: '0471940219-4',
    nome_contribuinte: 'CLAUDIO ALVES SIMOES',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 24',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005429,
    numero_contribuinte: '0471940220-8',
    nome_contribuinte: 'MARIANNE IRMGARD KARSTEN',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 34',
    bairro: 'JABAQUARA',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005430,
    numero_contribuinte: '0471940221-6',
    nome_contribuinte: 'PENTAGONAL EMP IMOBIL LTDA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 44',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005431,
    numero_contribuinte: '0471940222-4',
    nome_contribuinte: 'PHILOMENA PINA FIGUEIREDO PINTO',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 54',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005432,
    numero_contribuinte: '0471940223-2',
    nome_contribuinte: 'MARIA APARECIDA DA SILVA FERREIRA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 64',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005433,
    numero_contribuinte: '0471940224-0',
    nome_contribuinte: 'RAFAEL GRECCO MACHADO',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 74',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005434,
    numero_contribuinte: '0471940225-9',
    nome_contribuinte: 'ANTONIO CARLOS FOLGUERAL RODRIGUES',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 84',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005435,
    numero_contribuinte: '0471940226-7',
    nome_contribuinte: 'PENTAGONAL EMP IMOBIL LTDA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 94',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005436,
    numero_contribuinte: '0471940227-5',
    nome_contribuinte: 'PENTAGONAL EMP IMOBIL LTDA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 104',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005437,
    numero_contribuinte: '0471940228-3',
    nome_contribuinte: 'REGINALDO SOARES',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP 114',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005438,
    numero_contribuinte: '0471940229-1',
    nome_contribuinte: 'CLAUDIA CORREA BUENO',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP 124',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005439,
    numero_contribuinte: '0471940230-5',
    nome_contribuinte: 'MARIA DE JESUS MONTEIRO GUIMARAES',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 134',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005440,
    numero_contribuinte: '0471940231-3',
    nome_contribuinte: 'CRISTIANO CARVALHO DE OLIVEIRA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 144',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005441,
    numero_contribuinte: '0471940232-1',
    nome_contribuinte: 'PENTAGONAL EMP IMOBIL LTDA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 109,
    complemento: 'AP. 132',
    bairro: 'VL. GUARANI',
    cep: '04310-050',
    area_terreno: 921,
    area_construida: 90,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005442,
    numero_contribuinte: '0471940233-1',
    nome_contribuinte: 'PENTAGONAL EMP IMOBIL LTDA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 11',
    bairro: '',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005443,
    numero_contribuinte: '0471940234-8',
    nome_contribuinte: 'HERNANI JOAQUIM PINTO LOPES',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP. 12',
    bairro: 'VILA GUARANI',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005444,
    numero_contribuinte: '0471940235-6',
    nome_contribuinte: 'ANNITA PUERTAS PETIT',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 13',
    bairro: '',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005445,
    numero_contribuinte: '0471940236-4',
    nome_contribuinte: 'JOSE FERREIRA MARCOS',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 14',
    bairro: '',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005446,
    numero_contribuinte: '0471940237-2',
    nome_contribuinte: 'VALDECI GIRARDI MACHADO',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 21',
    bairro: 'VILA GUARANI',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005447,
    numero_contribuinte: '0471940238-0',
    nome_contribuinte: 'MARIA MARQUES DOS SANTOS FILHA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 22',
    bairro: 'VILA GUARANI',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005448,
    numero_contribuinte: '0471940239-9',
    nome_contribuinte: 'MARCELO DE MOURA MARQUES JUNIOR',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 23',
    bairro: '',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005449,
    numero_contribuinte: '0471940240-2',
    nome_contribuinte: 'HUMBERTO LUIZ SILVEIRA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 24',
    bairro: '',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005450,
    numero_contribuinte: '0471940241-0',
    nome_contribuinte: 'MOACYR DAS NEVES FARIA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 31',
    bairro: 'VILA GUARANI',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005451,
    numero_contribuinte: '0471940242-9',
    nome_contribuinte: 'AUDETE RODRIGUES CARLOTA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 32',
    bairro: 'VILA GUARANI',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005452,
    numero_contribuinte: '0471940243-7',
    nome_contribuinte: 'CARMEN GARCIA SULLER MARZA',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 33',
    bairro: 'VILA GUARANI',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005453,
    numero_contribuinte: '0471940244-5',
    nome_contribuinte: 'CARLOS ROBERTO ZANELATO',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 34',
    bairro: 'VILA MARIANA',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 1005454,
    numero_contribuinte: '0471940245-3',
    nome_contribuinte: 'MARIA ALVES DAS DORES',
    nome_logradouro: 'RUA GUARATUBA',
    numero: 51,
    complemento: 'AP 41',
    bairro: '',
    cep: '04310-050',
    area_terreno: 1765,
    area_construida: 70,
    tipo_uso: 'Apartamento em condomínio',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 947833,
    numero_contribuinte: '0451410115-1',
    nome_contribuinte: 'AUREA MAIA EGEA',
    nome_logradouro: 'RUA PIRITUBA',
    numero: 357,
    complemento: '',
    bairro: '',
    cep: '04052-120',
    area_terreno: 93,
    area_construida: 154,
    tipo_uso: 'Residência',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 914433,
    numero_contribuinte: '0430080045-6',
    nome_contribuinte: 'CARLOS NELY CLEMENTINO DE OLIVEIRA',
    nome_logradouro: 'RUA VIEIRA DE ALMEIDA',
    numero: 180,
    complemento: '',
    bairro: 'IPIRANGA',
    cep: '04268-040',
    area_terreno: 146,
    area_construida: 154,
    tipo_uso: 'Residência',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 914434,
    numero_contribuinte: '0430080046-4',
    nome_contribuinte: 'VERA REGINA COPRIVA DE SOUZA SANTOS',
    nome_logradouro: 'RUA VIEIRA DE ALMEIDA',
    numero: 176,
    complemento: '',
    bairro: '',
    cep: '04268-040',
    area_terreno: 146,
    area_construida: 154,
    tipo_uso: 'Residência',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 914435,
    numero_contribuinte: '0430080047-2',
    nome_contribuinte: 'SERGIO AUGUSTO',
    nome_logradouro: 'RUA SALVADOR SIMOES',
    numero: 172,
    complemento: '',
    bairro: '',
    cep: '04276-000',
    area_terreno: 150,
    area_construida: 153,
    tipo_uso: 'Residência',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 914436,
    numero_contribuinte: '0430080048-0',
    nome_contribuinte: 'JORGE UEMOTO',
    nome_logradouro: 'RUA SALVADOR SIMOES',
    numero: 168,
    complemento: '',
    bairro: '',
    cep: '04276-000',
    area_terreno: 150,
    area_construida: 153,
    tipo_uso: 'Residência',
    tipo_terreno: 'Normal',
  },
  {
    sampleid: 914437,
    numero_contribuinte: '0430090001-9',
    nome_contribuinte: 'ANTONIO TEIXEIRA DE ALMEIDA BRANDAO',
    nome_logradouro: 'RUA DR MARIO VICENTE',
    numero: 1230,
    complemento: 'E 1238',
    bairro: 'IPIRANGA',
    cep: '04270-002',
    area_terreno: 60,
    area_construida: 100,
    tipo_uso: 'Loja e residência (predominância comercial)',
    tipo_terreno: 'De esquina',
  },
  {
    sampleid: 914438,
    numero_contribuinte: '0430090002-7',
    nome_contribuinte: 'ERNESTO GEROLAMO COLOMBO',
    nome_logradouro: 'RUA DR MARIO VICENTE',
    numero: 1248,
    complemento: '',
    bairro: 'IPIRANGA',
    cep: '04270-002',
    area_terreno: 500,
    area_construida: 520,
    tipo_uso: 'Oficina',
    tipo_terreno: 'Normal',
  },
];
